# Generated by Django 2.2.10 on 2020-06-05 17:37

from django.db import migrations
#from radon.siteprofile.utils import create_sites


def update_site_forward(apps, schema_editor):
    #create_sites()
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('siteprofile', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_site_forward),
    ]
