# Generated by Django 2.2.10 on 2020-10-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('siteprofile', '0002_auto_20200605_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sitio',
        ),
    ]
