version: "3.8"
services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    env_file: .env
    command: /app/start.sh
    depends_on:
      - postgis
    ports:
      - "8000:8000"
    volumes:
      - ./docker/production/django/data/:/data/

  postgis:
      build:
        context: .
        dockerfile: ./docker/production/postgis/Dockerfile
      volumes:
        - ./docker/production/postgis/data:/var/lib/postgresql/data
        - ./docker/production/postgis/backups:/backups
      env_file: .env