# Generated by Django 2.2.10 on 2020-04-11 23:01

from django.db import migrations, models
import radon.users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gasera',
            field=models.ForeignKey(on_delete=models.SET(radon.users.utils.get_default_gasera), to='users.Gasera'),
        ),
    ]
