# Generated by Django 2.2.10 on 2020-04-24 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200411_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwdtemporal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
