# Generated by Django 2.2.10 on 2020-04-10 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('CONSUMIDOR', 'Consumidor'), ('STAFF', 'Staff')], default='CLIENTE', max_length=14),
        ),
        migrations.AddField(
            model_name='user',
            name='gasera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Gasera'),
        ),
    ]
