# Generated by Django 2.2.10 on 2020-04-11 19:47

from django.db import migrations, models
import radon.users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200410_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasera',
            name='nombre',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gasera',
            field=models.ForeignKey(default=radon.users.utils.get_default_gasera, on_delete=models.SET(radon.users.utils.get_default_gasera), to='users.Gasera'),
        ),
    ]
