# Generated by Django 2.2.10 on 2020-11-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200808_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='precio',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='precio',
            name='actual',
        ),
    ]
