# Generated by Django 2.2.10 on 2020-11-03 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201102_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasera',
            name='capacidad_total',
        ),
    ]
