# Generated by Django 2.2.10 on 2020-11-22 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georadon', '0001_initial'),
        ('users', '0006_remove_gasera_capacidad_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precio',
            name='gasera',
        ),
        migrations.CreateModel(
            name='MunicipioGasera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Gasera')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='georadon.Municipio')),
            ],
        ),
        migrations.AddField(
            model_name='gasera',
            name='municipio',
            field=models.ManyToManyField(through='users.MunicipioGasera', to='georadon.Municipio'),
        ),
        migrations.AddField(
            model_name='precio',
            name='municipio_gasera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.MunicipioGasera'),
        ),
    ]
