# Generated by Django 2.2.10 on 2020-11-14 00:47
from django.db import migrations
from django.conf import settings


def create_superuser(apps, schema_editor):
    User = apps.get_model('users', 'User')
    try:
        User.objects.get(email=settings.DJANGO_DEFAULT_SUPERUSER_EMAIL)
    except User.DoesNotExist:
        User.create_superuser(
            email=settings.DJANGO_DEFAULT_SUPERUSER_EMAIL,
            username=settings.DJANGO_DEFAULT_SUPERUSER_USERNAME
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_gasera_capacidad_total'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
