# Generated by Django 2.2.10 on 2020-12-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0007_auto_20201206_1947'),
        ('users', '0007_auto_20201122_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipiogasera',
            name='gasera',
        ),
        migrations.RemoveField(
            model_name='municipiogasera',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='precio',
            name='municipio_gasera',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gasera',
        ),
        migrations.DeleteModel(
            name='Gasera',
        ),
        migrations.DeleteModel(
            name='MunicipioGasera',
        ),
        migrations.DeleteModel(
            name='Precio',
        ),
    ]
