# Generated by Django 2.2.10 on 2021-01-09 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('users', '0008_auto_20201206_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Sucursal'),
        ),
    ]
