# Generated by Django 2.2.10 on 2021-01-30 20:05

from django.db import migrations, models
import radon.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', radon.users.models.ClienteManager()),
            ],
        ),
        migrations.CreateModel(
            name='Consumidor',
            fields=[
            ],
            options={
                'verbose_name': 'Consumidor',
                'verbose_name_plural': 'Consumidores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', radon.users.models.ConsumidorManager()),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', radon.users.models.OperadorManager()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', radon.users.models.StaffManager()),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
            ],
            options={
                'verbose_name': 'Super Usuario',
                'verbose_name_plural': 'Super Usuarios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', radon.users.models.SuperUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('CONSUMIDOR', 'Consumidor'), ('STAFF', 'Staff'), ('OPERARIO', 'Operario')], default='CONSUMIDOR', max_length=14),
        ),
    ]
