# Generated by Django 2.2.10 on 2021-05-12 17:57

from django.db import migrations
import radon.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210130_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', radon.users.models.AdminManager()),
            ],
        ),
    ]
