# Generated by Django 2.2.10 on 2020-11-23 21:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georadon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='geo',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=90),
        ),
    ]
