# Generated by Django 2.2.10 on 2020-12-07 01:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georadon', '0002_auto_20201123_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='clave',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=90, unique=True),
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
                ('nombre', models.CharField(max_length=80)),
                ('clave', models.CharField(max_length=13, unique=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georadon.Municipio')),
            ],
        ),
    ]
