# Generated by Django 2.2.10 on 2020-12-08 00:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georadon', '0003_auto_20201206_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='geo',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326),
        ),
    ]
