# Generated by Django 2.2.10 on 2021-01-24 23:06

from django.db import migrations


def migrar_localidades(apps, schema_editor):
    Sucursal = apps.get_model('market', 'Sucursal')
    Precio = apps.get_model('market', 'Precio')
    sucs = Sucursal.objects.all()
    for suc in sucs:
        precios = suc.precio_set.all()
        objs = []
        for precio in precios:
            precio.localidad = suc.localidad.all().first()
            objs.append(precio)
        Precio.objects.bulk_update(objs, ['localidad'])


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_precio_localidad'),
    ]

    operations = [
        migrations.RunPython(migrar_localidades),
    ]
