# Generated by Django 2.2.10 on 2021-01-25 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_poblar_localidad_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='municipio',
        ),
        migrations.AlterField(
            model_name='precio',
            name='localidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='georadon.Localidad'),
            preserve_default=False,
        ),
    ]
