# Generated by Django 2.2.10 on 2020-05-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=45, unique=True)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'DeviceType',
                'verbose_name_plural': 'DeviceTypes',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField(null=True, verbose_name='Capacidad del tanque')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instalacion',
                'verbose_name_plural': 'Instalaciones',
            },
        ),
        migrations.CreateModel(
            name='Wisol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=45, unique=True)),
                ('pac', models.CharField(max_length=80)),
                ('prototype', models.BooleanField(default=True)),
                ('deviceTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.DeviceType')),
            ],
            options={
                'verbose_name': 'Wisol',
                'verbose_name_plural': 'Wisols',
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('nivel', models.IntegerField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.Dispositivo')),
            ],
            options={
                'verbose_name': 'Lectura',
                'verbose_name_plural': 'Lecturas',
            },
        ),
    ]
