# Generated by Django 2.2.10 on 2020-03-05 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=45, unique=True)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'DeviceType',
                'verbose_name_plural': 'DeviceTypes',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='pac',
            field=models.CharField(default='1', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='prototype',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='capacidad',
            field=models.IntegerField(blank=True, verbose_name='Capacidad del tanque'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='serie',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='deviceTypeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iot.DeviceType'),
            preserve_default=False,
        ),
    ]
