# Generated by Django 2.2.10 on 2020-03-29 23:47
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_auto_20200304_1815'),
    ]

    operations = [
        CreateExtension('postgis'),
    ]
