# Generated by Django 2.2.10 on 2020-04-11 22:55
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_dispositivo_usuario'),
    ]

    operations = [
        CreateExtension('postgis'),
    ]
