# Generated by Django 2.2.10 on 2020-03-29 23:49

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import fromstr
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_install_postgis'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=fromstr('POINT(0 0)'), srid=4326),
            preserve_default=False,
        ),
    ]
