# Generated by Django 2.2.10 on 2020-05-12 15:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_instalacion_postgis'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
