# Generated by Django 2.2.10 on 2020-04-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_dispositivo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
