# Generated by Django 2.2.10 on 2020-05-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_auto_20200516_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='calendarizado',
            field=models.BooleanField(default=False, verbose_name='Indica si se esta a la espera de ser surtido.'),
        ),
    ]
