# Generated by Django 2.2.10 on 2020-04-24 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iot', '0006_auto_20200413_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumidor', to=settings.AUTH_USER_MODEL)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instalacion',
                'verbose_name_plural': 'Instalaciones',
            },
        ),
    ]
