# Generated by Django 2.2.10 on 2020-04-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_dispositivo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivo',
            old_name='user',
            new_name='usuario',
        ),
    ]
