# Generated by Django 2.2.10 on 2020-08-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_dispositivo_calendarizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='folio',
            field=models.CharField(default=0, max_length=10, unique=True, verbose_name='Folio de Instalación'),
            preserve_default=False,
        ),
    ]
