# Generated by Django 2.2.10 on 2020-09-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_lectura_nivel_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
