# Generated by Django 2.2.10 on 2020-10-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_auto_20200903_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='nombre',
            field=models.CharField(default='Casa', max_length=45, verbose_name='Nombre del dispositivo'),
        ),
    ]
