# Generated by Django 2.2.10 on 2020-10-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0010_dispositivo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
