# Generated by Django 2.2.10 on 2020-10-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_auto_20201030_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='entidad',
            field=models.IntegerField(null=True, verbose_name='Entidad federativa'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='localidad',
            field=models.IntegerField(null=True, verbose_name='Localidad del dispositivo'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='municipio',
            field=models.IntegerField(null=True, verbose_name='Municipio'),
        ),
    ]
