# Generated by Django 2.2.10 on 2020-11-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0012_auto_20201031_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
    ]
