# Generated by Django 2.2.10 on 2020-12-07 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('iot', '0013_dispositivo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='entidad',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Sucursal'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='georadon.Localidad'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='georadon.Municipio'),
            preserve_default=False,
        ),
    ]
