# Generated by Django 2.2.10 on 2020-12-08 01:47

from django.conf import settings
from django.db import migrations, models
import radon.users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201206_1947'),
        ('iot', '0014_auto_20201206_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='usuario',
            field=models.ForeignKey(default=radon.users.utils.get_default_user, on_delete=models.SET(radon.users.utils.get_default_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
