# Generated by Django 2.2.10 on 2020-12-16 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0015_auto_20201207_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lectura',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lectura',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
