# Generated by Django 2.2.10 on 2020-12-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0016_auto_20201216_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='status',
            field=models.CharField(choices=[('VERDE', 'Verde'), ('ROJO', 'Rojo'), ('AMARILLO', 'Amarillo')], default='VERDE', max_length=25, verbose_name='Status del dispositivo'),
        ),
    ]
