# Generated by Django 2.2.10 on 2020-12-27 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0017_dispositivo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Sucursal'),
        ),
    ]
