# Generated by Django 2.2.10 on 2021-01-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0018_auto_20201227_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='calle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='colonia',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='cp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
