# Generated by Django 2.2.10 on 2021-05-12 17:58

from django.db import migrations


def crear_hw_fw_append(apps, schema_editor):
    HwTag = apps.get_model('iot', 'Hardware')
    FwTag = apps.get_model('iot', 'Firmware')
    Wisol = apps.get_model('iot', 'Wisol')
    hw = HwTag.objects.create(tag='0.0.0', descripcion='Hardware Desconocido')
    fw = FwTag.objects.create(tag='0.0.0', descripcion='Firmware Desconocido')
    wisols = Wisol.objects.all()
    wisols.update(hardware=hw, firmware=fw)


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0020_auto_20210512_1257'),
    ]

    operations = [
        migrations.RunPython(crear_hw_fw_append),
    ]
