# Generated by Django 2.2.10 on 2020-11-13 19:28

from django.db import migrations
from radon.contrib.sites.utils import create_sites


def poblar_hosts(apps, schema_editor):
    create_sites()


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(poblar_hosts),
    ]
