# Generated by Django 2.2.10 on 2020-11-13 19:28

from django.db import migrations
from django.conf import settings
from django_hosts.resolvers import get_host_patterns


def poblar_hosts(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    settings.PARENT_HOST
    for host in get_host_patterns():
        domain = f'{host.regex}.{settings.PARENT_HOST}'
        obj, created = Site.objects.get_or_create(domain=domain, name=domain)


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(poblar_hosts),
    ]
