# Generated by Django 2.2.10 on 2020-05-16 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='gasera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Gasera'),
            preserve_default=False,
        ),
    ]
