# Generated by Django 2.2.10 on 2020-05-22 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_vehiculo_gasera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
