# Generated by Django 2.2.10 on 2020-05-24 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200523_1939'),
        ('rutas', '0003_auto_20200522_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Precio'),
            preserve_default=False,
        ),
    ]
