# Generated by Django 2.2.10 on 2020-12-07 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('rutas', '0006_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornada',
            name='gasera',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='gasera',
        ),
        migrations.AddField(
            model_name='jornada',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.Sucursal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.Sucursal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Precio'),
        ),
    ]
