# Generated by Django 2.2.10 on 2021-01-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0007_auto_20201206_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rutas.Jornada'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='orden',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden del dispositivo dentro de una ruta.'),
        ),
    ]
