# Generated by Django 2.2.10 on 2021-01-09 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0009_auto_20210107_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rutas.Pedido'),
        ),
    ]
