# Generated by Django 2.2.10 on 2021-01-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0010_mensaje_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutas.Pedido'),
        ),
    ]
