# Generated by Django 2.2.10 on 2021-01-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0011_auto_20210109_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ('-publicacion',)},
        ),
    ]
