# Generated by Django 2.2.10 on 2021-05-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0012_auto_20210116_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='rutas.Pedido'),
        ),
    ]
